version: '3.7'

services:

    signalserver:
        container_name: signal-server
        hostname: signal-server
        stdin_open: true
        tty: true
        volumes:
          - ./:/home/SignalServer
        build:
            context: ./
            dockerfile: Docker/Dockerfile
        ports:
          - 500:500
